Fixed `hivernate-validator` error message evaluation vulnerability
strongbox/strongbox pull request #1833
Opened 2020-09-14 01:56 UTC by sbespalov

# Pull Request Description

Fixed possible vulnerability with validation error messages evaluation.

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

2020-09-14 15:17 UTC, carlspring requested changes
LGTM, but we should have a test for it as well. :)

2020-09-15 02:59 UTC, sbespalov commented
> LGTM, but we should have a test for it as well. :)

@carlspring requested test provided

2020-09-15 09:15 UTC, carlspring approved these changes
LGTM, thanks for the test! :)

2020-09-16 21:54 UTC, steve-todorov approved these changes
LGTM, tested it manually as well and it works. The magic inside `escapeMessageValue` is cool! :D

2020-09-16 22:01 UTC, merged

2020-09-16 22:03 UTC, carlspring commented
Thanks for testing it! :)

Also, special thanks to XiaoC for reporting this and for providing an easy to reproduce exploit (in private), so that we could sort this out quickly! :)